### ISSUE TITLE
New Tweeters Volunteer: @DRIgnazGortngschirl

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/volunteer#85]
Following up on https://github.com/ethereumclassic/tweets-eth_classic/issues/19, this issue is to document the on-boarding process of a new user to the @ethereumclassic/tweeters team.

The new on-boarding process requires some [checks](https://github.com/IstoraMandiri/volunteer/blob/patch-1/README.md#on-boarding) to help keep the org secure.

This issue is open to everyone including the new volunteer to provide additional details or objections before existing volunteers make a recommendation to @ethereumclassic org admins to add as a volunteer to help manage tweets.

| Volunteer | @DRIgnazGortngschirl |
|---|---|
| 2FA | Unknown |
| Contributions | [Community Calls, https://etc-network.info](https://www.youtube.com/watch?v=zvL9hu46kZQ) |
| Anti-Sybil | [Pass](https://www.youtube.com/watch?v=zvL9hu46kZQ) |

**Comment by DRIgnazGortngschirl** [comment]
Just enabled 2FA 

![2FA](https://media.discordapp.net/attachments/1017496651193122998/1031096791694856212/image0.jpg?width=293&height=635)

**Comment by realcodywburns** [comment]
invite sent

**Comment by IstoraMandiri** [comment]
@RIgnazGortngschirl please confirm in this thread once you have accepted the invite, and I'll add you to the Tweeters group.

EDIT: Looks like you have been added to @ethereumclassic/tweeters, welcome on board!
