### ISSUE TITLE
New Tweeters Volunteer: @TheCrowbill 

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/volunteer#86]
Following up on https://github.com/ethereumclassic/tweets-eth_classic/issues/19, this issue is to document the on-boarding process of a new user to the @ethereumclassic/tweeters team.

The new on-boarding process requires some [checks](https://github.com/IstoraMandiri/volunteer/blob/patch-1/README.md#on-boarding) to help keep the org secure.

This issue is open to everyone including the new volunteer to provide additional details or objections before existing volunteers make a recommendation to @ethereumclassic org admins to add as a volunteer to help manage tweets.

| Volunteer | @TheCrowbill |
|---|---|
| 2FA | Unknown |
| Contributions | Unknown |
| Anti-Sybil | Unknown |

**Comment by TheCrowbill** [comment]
2FA is activated.
A PR just submitted replaces my expired PGP key with one newly generated.

**Comment by TheCrowbill** [comment]
As to anti-Sybiling, I don't mind doxxing myself if needed.

**Comment by realcodywburns** [comment]
invite sent

**Comment by IstoraMandiri** [comment]
@TheCrowbill you have been invited to @ethereumclassic/tweeters, welcome on board!

**Comment by TheCrowbill** [comment]
Invite accepted
