### ISSUE TITLE
New Tweeters Volunteer: @w1g0

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/volunteer#87]
Following up on https://github.com/ethereumclassic/tweets-eth_classic/issues/19, this issue is to document the on-boarding process of a new user to the @ethereumclassic/tweeters team.

The new on-boarding process requires some [checks](https://github.com/IstoraMandiri/volunteer/blob/patch-1/README.md#on-boarding) to help keep the org secure.

This issue is open to everyone including the new volunteer to provide additional details or objections before existing volunteers make a recommendation to @ethereumclassic org admins to add as a volunteer to help manage tweets.

| Volunteer | @w1g0 |
|---|---|
| 2FA | Unknown |
| Contributions | Many ETC Calls, Organizing on Discord |
| Anti-Sybil | [Pass](https://www.youtube.com/watch?v=zvL9hu46kZQ) |

**Comment by ghost** [comment]
@IstoraMandiri, is there another way to prove this?
![2022-10-16_12h00_50](https://user-images.githubusercontent.com/67763069/196029386-f4887e24-ba2c-4be8-9a3d-1734a474aa82.png)

**Comment by realcodywburns** [comment]
invite sent

**Comment by IstoraMandiri** [comment]
@w1g0 please confirm in this thread once you have accepted the invite, and I'll add you to the Tweeters and Web Maintainers group.

**Comment by ghost** [comment]
✅ Accepted

**Comment by IstoraMandiri** [comment]
Looks like you have been added to @ethereumclassic/tweeters, welcome on board!
