### ISSUE TITLE
Request to to add to org: Donald McIntyre 

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/volunteer#93]
Requesting that Donald McIntyre is added to the ETC GitHub org, so I can add him as a Website maintainer.

| Volunteer | @DonaldMcIntyre |
|---|---|
| 2FA | "Yes" |
| Contributions | Etherplan, etc. |
| Anti-Sybil | Major Contributor, verified through discord this github is his |

@realcodywburns

**Comment by IstoraMandiri** [comment]
Update

> ... now that it is public I can tell you that the ETC Coop hired me in part to contribute more to the ethereumclassic.org blog, videos, livestreams, and community call.

**Comment by realcodywburns** [comment]
Invitation sent 📨

**Comment by IstoraMandiri** [comment]
Welcome @DonaldMcIntyre

**Comment by DonaldMcIntyre** [comment]
Thank you!

**Comment by DonaldMcIntyre** [comment]
Hi, I was invited by @IstoraMandiri to be a "website maintainer" as an independent ETC volunteer. Before I was a maintainer while I was an employee of the ETC Cooperative, but now I would be happy to be help as a volunteer.

**Comment by IstoraMandiri** [comment]
cc @realcodywburns , requesting the adding of @DonaldMcIntyre back as a contributor (to website and tweets groups)
